# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 690a99a5a77567867c67bdfb00f00e04d3c7bc36693922297a16e93d747ac4898295b262a243b839b4462b73d2a345aa1046cff0ee4a868cf2f5f9b9526d5de2

test:
  secret_key_base: a3abff1602105a6a2940acd4057668c3219ae6684715e22e0690a435e4265222781717ac6174538ec18afc612f433ba538819e5d6eceefd38112f9572aa9bb60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
